version: "0.2"
language: en
words:
  - aarch
  - abled
  - Achstetter
  - ADAFRUIT
  - addch
  - addstr
  - afen
  - akatran
  - apidoc
  - Arduipi
  - AREF
  - argparser
  - armhf
  - armv
  - Atmel
  - atmelavr
  - atmelmegaavr
  - atmelsam
  - ATSAMD
  - ATTINY
  - attroff
  - attron
  - ATXMEGA
  - ATXMEGAD
  - autosectionlabel
  - Avamander
  - bdist
  - berryfied
  - blogspot
  - bndy
  - bootloader
  - BPLUS
  - bufptr
  - bugprone
  - bysource
  - bytearray
  - calcsize
  - cbps
  - cbreak
  - ccache
  - ccmake
  - cepin
  - CFLAGS
  - CHIPINFO
  - CLANGTIDY
  - classname
  - CLKSEL
  - codecov
  - Coliz
  - cond
  - Configurators
  - cpack
  - CPHA
  - cpixip
  - CPPCHECK
  - cppreference
  - CPUFLAGS
  - crclength
  - CRCO
  - CROSSCOMPILING
  - crossunix
  - crossunixccompiler
  - cspin
  - cstdio
  - CTRLA
  - CTRLB
  - datarate
  - datasheet
  - Datasheets
  - DBUILDSWIGNODE
  - DCMAKE
  - DEFAULTPINS
  - deinit
  - DIRCLR
  - DIRSET
  - Disabl
  - Doherty
  - Doxyfile
  - doxygen
  - doxygenfile
  - doxygenfunction
  - doxygengroup
  - doxygenpage
  - doxygenvariable
  - DPICO
  - dpkg
  - DSOFT
  - DSOFTSPI
  - dstroy
  - DYNPD
  - ENAA
  - endforeach
  - endfunction
  - endparblock
  - endverbatim
  - endwin
  - Engelke
  - enumvalue
  - espressif
  - Fals
  - farconada
  - fdevopen
  - FETCHCONTENT
  - fsanitize
  - fsel
  - fstack
  - ftime
  - genindex
  - gettingstarted
  - gnueabihf
  - gnux
  - GPIO
  - gpiochip
  - gpiod
  - Gunasekara
  - Hallard
  - HCURR
  - HILVLEN
  - HLINE
  - HMISO
  - HMOSI
  - HSCLK
  - hspi
  - Ikpeoha
  - imgui
  - INPT
  - INTCTRL
  - INTCTRLA
  - Interprocedural
  - intersphinx
  - iomanip
  - ITSYBITSY
  - Jannis
  - jscrane
  - KBPS
  - Konde
  - kripton
  - ldconfig
  - ldiaz
  - libboost
  - libc
  - libmaple
  - libncurses
  - librf
  - linaro
  - linenos
  - literalinclude
  - LITTLEWIRE
  - LOLVLEN
  - lossiness
  - LPSTR
  - LPWSTR
  - lsbmode
  - lwiring
  - Makefiles
  - Maniacbug
  - markdownlint
  - marm
  - MBED
  - MBPS
  - MCUSR
  - MEDLVLEN
  - MEGAAVR
  - mfloat
  - mfpu
  - microcontroller
  - milisec
  - millis
  - milliwatts
  - MOSI
  - MRAA
  - MSBFIRST
  - MSVC
  - mtune
  - Multiceiver
  - mypy
  - nerdralph
  - newlib
  - nocbreak
  - noecho
  - nullptr
  - Ofast
  - OLED
  - OUTCLR
  - OVFINTLVL
  - parblock
  - Pastore
  - pgmspace
  - PICO
  - PIGPIO
  - PIMORONI
  - PINB
  - pingpair
  - pinout
  - pkgs
  - PLOS
  - PMIC
  - PORTA
  - PORTB
  - PORTC
  - PORTD
  - Portenta
  - PORTF
  - postargs
  - postinst
  - postrm
  - POWERUP
  - preargs
  - premain
  - prescalar
  - Prescaler
  - println
  - PRIPSTR
  - PROGMEM
  - pthread
  - purinda
  - pypi
  - pyproject
  - QTPY
  - Quigg
  - raspi
  - REALPATH
  - rpmbuild
  - RXADDR
  - rxbuff
  - SAMD
  - sccache
  - sclk
  - seealso
  - Seow
  - SERCOM
  - setuptools
  - SOFTSPI
  - SOVERSION
  - spaniakos
  - SPARFUN
  - Sparkfun
  - Speedz
  - SPID
  - spidev
  - SPIUART
  - sprintf
  - stanleyseow
  - stby
  - stddef
  - stdlib
  - STREQUAL
  - strresult
  - ststm
  - sunxi
  - suppr
  - SWITCHCAPVCC
  - sysroot
  - tableofcontents
  - TEENSYDUINO
  - THINGPLUS
  - toctree
  - TOLOWER
  - transfern
  - transfernb
  - txbuff
  - UART
  - undoc
  - unexport
  - userspace
  - uspi
  - vect
  - venv
  - vfpv
  - virtualenv
  - vpfv
  - VSPI
  - Wcast
  - Wconversion
  - WDCE
  - WDIE
  - Wdouble
  - WDRF
  - wdtcsr
  - Wduplicated
  - Werror
  - Wextra
  - Wformat
  - WGMODE
  - WIRINGPI
  - Wlogical
  - Wmisleading
  - Wnon
  - Wnull
  - Woverloaded
  - Wpedantic
  - Wshadow
  - Wsign
  - Wunused
  - Wuseless
  - XMEGA
  - Yagarto
  - zador
ignorePaths:
  - .env/**
  - .venv/**
  - env/**
  - venv/**
  - "**.clang-tidy"
  - "**.clang-format"
  - .gitignore
  - "**/*.{yml,yaml}"
  - utility/RPi/bcm2835.*
  - Makefile*
  - make.bat
  - Doxyfile
  - configure
  - CHANGELOG.md
